const WIDTH = 1280;
const HEIGHT = 400;
const BORDER_WIDTH = 15;
const CONTENT_WIDTH = WIDTH - BORDER_WIDTH - BORDER_WIDTH;
const CONTENT_HEIGHT = HEIGHT - BORDER_WIDTH - BORDER_WIDTH;

export const SCREEN = {
  WIDTH: WIDTH,
  HEIGHT: HEIGHT,
  BORDER_WIDTH: BORDER_WIDTH,
  CONTENT_WIDTH: CONTENT_WIDTH,
  CONTENT_HEIGHT: CONTENT_HEIGHT
}

export const PEDAL_CONFIG = {
  MIN: 0,
  MAX: 100
}